---
ID: "8214f440-d23c-5274-bde8-4a687c7723ca"
Parent: "b5d4f0d3-baae-50aa-959e-55d3edb619a4"
Template: "b5d4f0d3-baae-50aa-959e-55d3edb619a4"
Path: "/sitecore/templates/Project/starterkit/Styleguide-FieldUsage-Link/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230612T215050Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d58ffb3e-fb3d-4d66-96b0-f1f2333ea117"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230612T215050Z
