---
ID: "077c9017-00c1-5748-97dd-7d7f464d1a2e"
Parent: "9f95a3a7-0ac3-56b5-bc54-3a4d90faf3a0"
Template: "9f95a3a7-0ac3-56b5-bc54-3a4d90faf3a0"
Path: "/sitecore/templates/Project/starterkit/Styleguide-Layout-Reuse Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230612T215111Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d0f3da1c-bbb3-4c67-bd51-cfc6922cf2db"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230612T215111Z
