---
ID: "0c3c762b-cdb9-5cad-bb71-faee3d8cc744"
Parent: "44809ae9-6d95-5034-9d1c-25f9cbea3b94"
Template: "44809ae9-6d95-5034-9d1c-25f9cbea3b94"
Path: "/sitecore/templates/Project/starterkit/Styleguide-Multilingual/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230612T215100Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ab121dc7-51dc-42ea-b0d8-4076dcfc4a90"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230612T215100Z
