---
ID: "7bb237ff-fb50-5df5-a62b-fe2ceab3d4e9"
Parent: "1a9930f4-ad1b-513b-8abe-5aa9e4ca477b"
Template: "1a9930f4-ad1b-513b-8abe-5aa9e4ca477b"
Path: "/sitecore/templates/Project/starterkit/Styleguide-RouteFields/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230612T215101Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0cf6218e-caff-4f26-9c10-fc4ad4e18e95"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230612T215101Z
