---
ID: "5068fef6-0d5d-5d24-bbdc-7fbfa5704a0f"
Parent: "acb74b3e-ccbb-5bdb-a557-c4fc149795cf"
Template: "acb74b3e-ccbb-5bdb-a557-c4fc149795cf"
Path: "/sitecore/templates/Project/starterkit/Styleguide-FieldUsage-RichText Rendering Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230612T215106Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "39c87eb3-07c5-4991-bb14-218796c8f0fc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230612T215106Z
